services:
  - type: web
    name: doorbell-project
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y cmake
      pip install -r requirements.txt
    startCommand: gunicorn app:app
