services:
  - type: web
    name: doorbell-project
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y cmake build-essential
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:5001 app:app
